kind: pipeline
name: build

steps:
  # Default clone does not fetch tags
- name: fetch-tags
  image: docker:git
  commands:
    - git fetch --tags
    - echo "export OF_BUILD_DATE=$(date -Iseconds)" >> build_metadata
    - echo "export OF_GIT_COMMIT=$(git rev-parse HEAD)" >> build_metadata
    - echo "export OF_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> build_metadata
    - echo "export OF_GIT_RELEASE=$(git describe --long --always)" >> build_metadata

  # Install dependencies and test the python code
- name: overflow
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mythern/overflow
    context: .
    auto_tag: true
    cache_from:
      - mythern/overflow:latest
    purge: false
  when:
    event: [push]

# Copy compose-file
- name: configure
  image: appleboy/drone-scp
  settings:
    host: ace.ulv.io
    port: 22000
    username: root
    key:
      from_secret: ssh_key
    target: /srv/www/overflow/
    source: docker-compose.yml
  when:
    event: [push]

  # Pull fresh images, restart, cleanup and report status
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: ace.ulv.io
    port: 22000
    username: root
    key:
      from_secret: ssh_key
    command_timeout: 600s
    script:
      - cd /srv/www/overflow
      - sed -i 's#src/##g' docker-compose.yml
      - sed -i '/build:/d' docker-compose.yml
      - sed -i '/dockerfile:/d' docker-compose.yml
      - sed -i '/context:/d' docker-compose.yml
      - docker-compose pull
      - docker-compose down
      - docker-compose up -d -t 600
      - docker image prune -f
      - docker-compose ps
  when:
    event: [push]

