kind: pipeline
name: build

steps:
# Install dependencies and test the python code
- name: build-and-push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mythern/overflow
    context: .
    build_args:
      - build_date=${DRONE_BUILD_STARTED}
      - git_tag=${DRONE_TAG}
      - git_sha=${DRONE_COMMIT}
    auto_tag: true
    tags:
      - latest
    cache_from:
      - mythern/overflow:latest
    purge: false
  when:
    event: [tag]

# Copy compose-file
- name: configure
  image: appleboy/drone-scp
  settings:
    host: ace.ulv.io
    port: 22000
    username: root
    key:
      from_secret: ssh_key
    target: /srv/www/overflow/
    source: docker-compose.yml
  when:
    event: [tag]

  # Pull fresh images, restart, cleanup and report status
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: ace.ulv.io
    port: 22000
    username: root
    key:
      from_secret: ssh_key
    command_timeout: 600s
    script:
      - cd /srv/www/overflow
      - docker-compose pull
      - docker-compose down
      - docker-compose up -d -t 600
      - docker image prune -f
      - docker-compose ps
  when:
    event: [tag]

