version: '3.6'

services:
  # Django container
  overflow:
    build:
      dockerfile: Dockerfile
      context: .
    image: mythern/overflow
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:13571"
    depends_on:
      - db
      - redis
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.backend=overflow"
      - "traefik.frontend.rule=Host:overflow.no"
      - "traefik.protocol=http"
      - "traefik.port=80"

  # PostgreSQL container
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Cache container
  redis:
    image: redis:alpine
    restart: unless-stopped

# Define the Traefik network for auto detection from forward proxy
networks:
  traefik:
    external: true

