FROM node:alpine as builder

WORKDIR /app

RUN apk add --no-cache --virtual .gyp python git && apk del .gyp

COPY frontend/package.json frontend/tsconfig.json frontend/webpack.config.js frontend/.yarnrc frontend/yarn.lock ./
RUN yarn install --ignore-optional

COPY frontend/src/ src/
COPY .git .git
RUN yarn build:prod


FROM nginx:alpine as runner

COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
