services:
  # Django + Nginx container
  nginx:
    image: ghcr.io/myth/overflow:v7.1.2
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overflow.rule=Host(`overflow.no`)"
      - "traefik.http.routers.overflow.tls=true"
      - "traefik.http.routers.overflow.tls.certresolver=le"
    volumes:
      - ./uploads:/var/www/html/media

  # PostgreSQL container
  db:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - default

  # Cache container
  redis:
    image: docker.io/redis:alpine
    restart: unless-stopped
    networks:
      - default

# Define the Traefik network for auto detection from forward proxy
networks:
  default:
  traefik:
    external: true
