[tool.black]
line-length = 120
target-version = ['py311']

[tool.pylint]
max-line-length=120
target-version = ['py311']

[tool.poetry]
name = "overflow"
version = "6.0.0"
description = "overflow.no is the personal playground of Aleksander Skraastad. I'm a programmer, science & technology nerd, and outdoors enthusiast."
authors = ["Aleksander Skraastad <myth@overflow.no>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.27.0.post1"
Django = "^5.0.1"
django-cors-headers = "^4.3.1"
django-redis = "^5.4.0"
markdown2 = "^2.4.12"
psycopg2-binary = "^2.9.9"
python-decouple = "^3.8"
pillow = "^10.2.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
isort = "^5.13.2"
pylint = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
