[build-system]
requires = [
    # Minimum requirements for the build system to execute. PEP 508 specifications.
    "setuptools",
    "wheel",
]

[tool.black]
line-length = 120
target-version = ['py37']