# Generated by Django 2.2 on 2019-04-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190416_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
