# Generated by Django 3.0 on 2019-12-06 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_auto_20191207_0039"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostImage",
            new_name="Image",
        ),
    ]
