# Generated by Django 4.2 on 2023-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_auto_20191207_0044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
