# Generated by Django 5.0.2 on 2024-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_image_id_alter_post_id_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="raw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="read_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
