name: Docker build and deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and push
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: ./.github/actions/setup-docker
        with:
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write build metadata
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "export OF_BUILD_DATE=$(date -Iseconds)" >> build_metadata
          echo "export OF_GIT_COMMIT=${GITHUB_SHA}" >> build_metadata
          echo "export OF_GIT_BRANCH=master" >> build_metadata
          echo "export OF_GIT_RELEASE=${GITHUB_REF##*/}" >> build_metadata

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/myth/overflow:${{ env.TAG_NAME }}
            ghcr.io/myth/overflow:latest
